In [1]:
print("Lakku Lavanya");

Lakku Lavanya


# Data Analysis Using Python
## Electronics & Communication
### Section-B
#### Lakku Lavanya
##### Nellore

In [2]:
print(6+6)

12


## Python
- List
    - Mutable,[ ]
- Tuple 
    - Immutable,( )
- Strings
    - " ",' '
- Dict
    - { },Keys and values
- Sets
    - { },unique values
- Files
- Functions
- Oops

- Welcome To APSSDC
- **Welcome To APSSDC**
- ***Welcome To APSSDC***

In [3]:
import numpy
a = numpy.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [11]:
import numpy as np
a1 = np.array([[1,2,3],[2,3,4]])
print(a1)

[[1 2 3]
 [2 3 4]]


In [12]:
import numpy as np
a2 = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a2)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [15]:
a1.size


6

In [16]:
a1.ndim

2

In [17]:
a1.shape

(2, 3)

In [22]:
a1[0]

array([1, 2, 3])

In [27]:
a2[1:,2:]

array([[4],
       [5]])

In [30]:
np.random.randn()

1.378372793723994

In [31]:
np.random.randn(6)

array([ 0.80814787,  0.15458638,  0.14657105, -0.313637  ,  0.69570269,
       -0.20194007])

In [34]:
np.random.randn(1,20,10)

array([[[ 2.10791031e-01, -8.84237727e-01, -9.07346045e-01,
         -5.19075257e-01, -2.43644770e+00, -5.89033269e-01,
          8.23708794e-01, -1.25070640e+00,  5.55334281e-01,
         -8.37181771e-01],
        [ 7.92215251e-01, -1.20117661e+00,  1.33455196e-01,
          6.90534007e-02, -8.66914894e-01,  5.96920995e-01,
          6.43394127e-01,  2.21192053e+00, -6.32229302e-01,
          1.33936259e+00],
        [ 4.72401931e-01, -7.07688267e-01,  7.94726097e-01,
         -1.23115844e-01,  1.46104811e+00,  1.12763302e+00,
          1.54183089e+00, -3.51839537e-01,  6.25706200e-02,
         -5.76110266e-01],
        [-2.86469490e-01, -1.03455704e+00,  1.34905268e+00,
          1.34247463e+00, -1.08478236e+00,  1.03637776e+00,
         -1.53504054e+00, -6.18909922e-01,  2.88959213e-01,
         -4.53890741e-01],
        [ 1.87398214e+00,  8.40440072e-01,  6.14443062e-02,
         -9.08955073e-01, -1.37980931e+00, -1.46310293e+00,
         -1.47411969e+00, -1.39456505e+00, -8.319828

In [42]:
a = np.random.randint(1,20,10)
print(a)

[19 12  9  1 12  2  8  6 19 17]
